### ISSUE TITLE
New 'cache' attribute

### ISSUE THREAD

**Issue by PedroGabriel** [JohnnyTheTank/apiNG#105]
Hello,

I would love to see a new attribute that setup a cache for every API call.
This would allow to easily set things to be available offline.

Something like:
`cache`to enable/disable caching in this fetch.
if true,
check if there are any cache available, the attribute `lifetime` (timestamp) could be used to determine when fetch new data from API or use the cached one. If there's no connection, it always use the cached one.
Thanks for reading :)

**Comment by JohnnyTheTank** [comment]
I cannot implement this. the plugin structure is not capable of this needed cache structure
