### ISSUE TITLE
Create linkedin plugin

### ISSUE THREAD

**Issue by aberbenni** [JohnnyTheTank/apiNG#109]

**Comment by JohnnyTheTank** [comment]
hello @aberbenni,

which data would you like to get from linkedin?

**Comment by aberbenni** [comment]
Number of connections and recent posts of a user.

Number of followers and recent updates of a company page.

**Comment by JohnnyTheTank** [comment]
Okay, I will check the feasibility

**Comment by aberbenni** [comment]
Thanks @JohnnyTheTank

**Comment by JohnnyTheTank** [comment]
@aberbenni I checked the rest console: https://apigee.com/console/linkedin but the endpoints are not rich enough to build a plugin for this.

there is no public data available. you can can only display data of your own profile or of your own companys. for me, it's not enough to work on this plugin, sorry
