### ISSUE TITLE
 Settings dynamically my value in your component  attribute

### ISSUE THREAD

**Issue by savanevamara** [JohnnyTheTank/apiNG#111]
Hello,
I commend you for the creation of your library it facilitates the implementation of the flow of social networks, 
I am a little novice with angular but I understand that's principle, i  like know how to make your directive with parameters dynamic, 
I have a coded an application that saves settings some network social and Wikipedia and I arrive to recover my data views, i like use your components and make a binding of my settings dynamically in your attribute ?

**Comment by JohnnyTheTank** [comment]
I want to help you, but I don't understand what your Problem is

**Comment by savanevamara** [comment]
thank you for your reply,
I want to build an application that displays the flow of social networks, and the social networks parameters are dynamic, 
how I could use your library ?

**Comment by JohnnyTheTank** [comment]
aping works with dynamic Parameters. you can insert scope vars in all aping attributes

**Comment by savanevamara** [comment]
thank you
