### ISSUE TITLE
As a Dom Element and Attribute

### ISSUE THREAD

**Issue by msholly** [JohnnyTheTank/apiNG#112]
Hi Devs, is it possible to load apiNG as an attribute to a HTML tag?

In other Angular components (example Angular Tree Control) I can call

`<treecontrol attr1="" attr2=""`
or 
`<div treecontrol attr1="" attr2=""`

Sorry if I missed this in the documentation, but I didn't see any reference to 
`<div aping template-url=""`

Or something like that, and I could be missing something really simple of course. Love the work you did, really straightforward.

**Comment by JohnnyTheTank** [comment]
Hello msholly,

I can add this possibility easily in the next minutes.

With best regards

**Comment by JohnnyTheTank** [comment]
@msholly I've released [v1.4.1](https://github.com/JohnnyTheTank/apiNG/releases/tag/v1.4.1) and added the possibility to use apiNG with the html attribute `aping`.

Good idea!
