### ISSUE TITLE
Feed (live update/ auto refresh)

### ISSUE THREAD

**Issue by Eisa01** [JohnnyTheTank/apiNG#114]
Hi,
I want to use this in my project, however I need  the feed to be live or for it to auto refresh frequently in order to use it.
For example, I am searching for recent posts of #Cybersecurity in Twitter, I want it to update the feed every time a new post is created with #Cybersecurity.

Currently, the feed doesn't refresh at all,  and everytime I need to see latest conten.i have to refresh the page manually.

A way to make the feed live would be perfect, however if that is not feasible, then a way to refresh the feeds for example in each 3 minutes would suffice.

I wish that this can be implemented!

I'm really looking forward to hear your reply.
Thanks!

**Comment by JohnnyTheTank** [comment]
hello @Eisa01, thank you for your request. 

currently, apiNG has no refresh/reload feature, but I'm thinking about this.

in the meantime, I have a quickfix for you: http://plnkr.co/edit/4cVY9gqw1QcnxPIcfflK?p=preview

I hope this helps your

**Comment by Eisa01** [comment]
Hello @JohnnyTheTank, thank you for your response!

I have just finished implementing what you have provided. That is indeed a very smart solution and almost feasible.

However, one thing makes this unusable for my usecase.

The whole page refresh when there are a lot of resources makes things almost unreadable, additionally you can't scroll down to read since it keeps on refreshing.

To fix this, would it be possible to append newer results without refreshing older results?

Perhaps through a duplicate check, or comparing posts time to only find posts that are newer to the refresh date through another div that won't collide with this.

*fingers crossed*

**Comment by JohnnyTheTank** [comment]
Hello @Eisa01,

in theory, it's possible to implement this, but this would be a massive change in all plugins.
Currently, I have no time to work so much on apiNG.

sorry
